### ISSUE TITLE
broken on 9.2.2?

### ISSUE THREAD

**Issue by tolgraven** [GonzaloNV/Myo-Ableton#1]
Doesn't seem to work on 9.2.2. I can't figure out why because the UserConfiguration.txt looks to be in order, but logs throws 

4713 ms. RemoteScriptError: import Myo-basic
4713 ms. RemoteScriptError:

4713 ms. RemoteScriptError:
4713 ms. RemoteScriptError:
4713 ms. RemoteScriptError:
4713 ms. RemoteScriptError:
4714 ms. RemoteScriptError:
4714 ms. RemoteScriptError:
4714 ms. RemoteScriptError:
4714 ms. RemoteScriptError:
4714 ms. RemoteScriptError:
4714 ms. RemoteScriptError:
4714 ms. RemoteScriptError:
4714 ms. RemoteScriptError: ^

4714 ms. RemoteScriptError: SyntaxError
4714 ms. RemoteScriptError: :
4714 ms. RemoteScriptError: invalid syntax
4715 ms. RemoteScriptError:

4807 ms. RemoteScriptError:   File "
4807 ms. RemoteScriptError: <string>
4807 ms. RemoteScriptError: ", line
4808 ms. RemoteScriptError: 1
4808 ms. RemoteScriptError:

**Comment by tolgraven** [comment]
nvm i'm dumb

**Comment by GonzaloNV** [comment]
Hey man!

I just received everything. Did you get it to work? What was the problem?

Anything else I can help you with, just let me know.
I'm also in the middle of programming a simple application to output any
midi message of your choice from any of the gestures, so it should
supersede this one. It would also work in Windows, so that's nice...
I'll post it as soon as ready

Cheerio!

**Comment by tolgraven** [comment]
Hi. Never made/used any scripts based on the .txt thing before, only python. Just dumped it inside MIDI Remote Scripts, hence the issues hehe. At least in my installation there is no "User Remote Scripts" in that folder though, eventually realized it's supposed to go in ~/Library/Preferences/Ableton/Live 9.x.x/User Remote Scripts
works alright now

**Comment by GonzaloNV** [comment]
Oh, ok.
It's been a while since I posted the connector, so it may need some
clarification. I don't remember if the remote scripts path was properly
explained on the github

**Comment by DiegoJimenezTamame** [comment]
Hola. ¿Podrías echarme un cable? Tengo el mismo problema que este chico, pero no encuentro la solución. No me aparecen las carpetas ni los directorios de los que habla. No sé qué tengo que hacer y no consigo que Myo me funcione con Ableton Live 9.2.2. Tampoco me queda muy claro cuál es el script que debo utilizar. :S

Muchas gracias.

If you need me to write in English, just let me know.

**Comment by GonzaloNV** [comment]
No hay problema. Cuando llegue a casa lo miro.
Igual estoy casi seguro de que el problema son las carpetas ocultas. Por
defecto aparecen así.

Por curiosidad, ¿cómo viste el problema del mail anterior? ¿Hay algún foro
donde aparecen las preguntas y las respuestas, porque yo no lo vi. O sea,
pensaba que el contacto era solo por mail

**Comment by DiegoJimenezTamame** [comment]
Sólo he visto los comentarios de Tolgraven en esta página. Perdona, es que soy nuevo en esto y estoy un poco perdido.

**Comment by GonzaloNV** [comment]
Jaja, no yo también lo soy.  Por eso te preguntaba en qué página es que
estaban los comentarios

**Comment by DiegoJimenezTamame** [comment]
Jajaja, ok
¿Pero tú hiciste el conector, no?

**Comment by GonzaloNV** [comment]
Si, si. Eso sí

**Comment by DiegoJimenezTamame** [comment]
Entonces, espero tu respuesta. A ver si me puedes ayudar, porque estoy un poco preocupado. Me compré Myo principalmente para utilizarlo con Ableton, y de momento no hay manera... :'(

**Comment by GonzaloNV** [comment]
Preguntas de rigor:
¿qué sistema operativo estás usando?
¿tenés activado que se vean las carpetas ocultas?
¿tenés la última versión del MYO Connect?

**Comment by DiegoJimenezTamame** [comment]
Tengo MacOS X El Capitan, he activado lo de las carpetas ocultas (aunque luego lo he desactivado, ahora mismo escribo desde el móvil), y creo que tengo la última versión de MYO Connect (creo que es 1.0.1)

**Comment by DiegoJimenezTamame** [comment]
Hola! Al final has tenido tiempo de mirar eso? Gracias!

**Comment by tolgraven** [comment]
dios mío

**Comment by tolgraven** [comment]
que directorios no tienes? en cualquier caso no necesitas mirar las carpetas ocultas.

Finder -> cmd+c el UserConfiguration.txt -> cmd+shift+g -> "~/Library/Preferences/Ableton/Live 9.2.2/User Remote Scripts" -> enter -> cmd+v

vale?

"~" es equivalente de "/Users/nombredeusario"

**Comment by DiegoJimenezTamame** [comment]
No me aparece la carpeta Ableton dentro de Library/Preferences. Creo que ese es el problema. ¿Qué debo hacer?

**Comment by tolgraven** [comment]
No es en el root Library, solo en el Library de tu usario ;)

**Comment by DiegoJimenezTamame** [comment]
Vale, pues entonces tengo un problema, porque no me aparece ninguna carpeta Librería en mi usuario

**Comment by DiegoJimenezTamame** [comment]
AH!!! Creo que lo he encontrado. Voy a probar Myo y te digo más tarde a ver si funciona.

**Comment by GonzaloNV** [comment]
Perdona la demora, pero aún no he vuelto a mi casa.
Prueba lo que ponen en esta direccion
https://www.ableton.com/answers/location-of-user-remote-scripts-folder-on-osx-mountain-lion-live-8-3-4

¡Saludos!

2015-10-06 18:02 GMT-03:00 DiegoJimenezTamame notifications@github.com:

> AH!!! Creo que lo he encontrado. Voy a probar Myo y te digo más tarde a
> ver si funciona.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GonzaloNV/Myo-Ableton/issues/1#issuecomment-146000059
> .

## 

¡Saludos!
Gonzalo

**Comment by tolgraven** [comment]
si porque es una carpeta oculta...

blah this is as far as my spanish stretches lol anyways that's why you press cmd+shift+g, then you can navigate to any folder, hidden or not, by typing in the path. So just copy exactly the path I wrote, then in Finder press cmd+shift+g, paste the path into the field then press enter and the folder will pop up. Then just copy the file there and you're all good...

**Comment by DiegoJimenezTamame** [comment]
Ok, I just did that, but it is still not working. :'( Could you make a short sketch for me? I mean, all the steps that I have to follow. Should I put the .txt inside the Ableton app folder? I'm just so lost. :(

**Comment by GonzaloNV** [comment]
I´m afraid that the only time I´ve ever used a Mac was when writing the
script, so I don´t know all this shortcuts.
Did you take a look at the guide on the github readme?
If you follow that, you will find a folder called User Remote Scripts.
Inside that one, you should copy the Myo-basic folder.

Once you did that, you open Ableton and under midi preferences, you should
find Myo-basic as a device. If that´s the case, you were succesful

On 6 October 2015 at 18:11, DiegoJimenezTamame notifications@github.com
wrote:

> Ok, I just did that, but it is still not working. :'( Could you make a
> short sketch for me? I mean, all the steps that I have to follow. Should I
> put the .txt inside the Ableton app folder? I'm just so lost. :(
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GonzaloNV/Myo-Ableton/issues/1#issuecomment-146002624
> .

## 

¡Saludos!
Gonzalo

**Comment by tolgraven** [comment]
Nah that's the same mistake I was making. Normally midi scripts go in the ableton app folder but this one is different and needs to be put in the folder I wrote. What about if you go to "~/Library/Preferences/Ableton/"? There should be subfolders in there for every version of Ableton you've used on that computer... They have to be there or Ableton wouldn't work. I still think you might be trying to go into the root Library folder...
The other thing you can do to navigate there is open Finder, then go into the "Go" menu press "alt" and there will be an extra entry for "Library"... that will take you into the Library dir for your user. Then just navigate from there...

**Comment by DiegoJimenezTamame** [comment]
Thanks guys, I just did it! I copied the file in the right place. For some reason, Ableton was not responding at the first instance. I reopened it once or twice and finally it got it, lol THANKS SO MUCH, DUDES!

**Comment by GonzaloNV** [comment]
Great to hear that!
Thanks for all the help, tolgraven

On 6 October 2015 at 18:19, DiegoJimenezTamame notifications@github.com
wrote:

> Thanks guys, I just did it! I copied the file in the right place. For some
> reason, Ableton was not responding at the first instance. I reopened it
> once or twice and finally it got it, lol THANKS SO MUCH, DUDES!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GonzaloNV/Myo-Ableton/issues/1#issuecomment-146005074
> .

## 

¡Saludos!
Gonzalo

**Comment by DiegoJimenezTamame** [comment]
Wow, seriously, thank you so much!

**Comment by tolgraven** [comment]
no woz

btw if you guys have max4live I'm about to start work on a M4L device that will do basically what this script does but with the ability to permanently assign to any parameter in the set instead of just blue-handing. But main thing I guess will be the ability to toggle back and forth between the sets of permanent assignments and blue hand-control. I'll keep you guys posted (and put it on github) if you're keen.

**Comment by GonzaloNV** [comment]
That would be cool indeed!

But if you want just a quick way to assign to some parameters permanently,
you can just not use the script. With the myo connector you are already
sending the MIDI data to Ableton.
If you deactivate the remote script, then you can just cmd+M and assign all
the parameters manually

On 6 October 2015 at 18:29, tolgraven notifications@github.com wrote:

> no woz
> 
> btw if you guys have max4live I'm about to start work on a M4L device that
> will do basically what this script does but with the ability to permanently
> assign to any parameter in the set instead of just blue-handing. But main
> thing I guess will be the ability to toggle back and forth between the sets
> of permanent assignments and blue hand-control. I'll keep you guys posted
> (and put it on github) if you're keen.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GonzaloNV/Myo-Ableton/issues/1#issuecomment-146007568
> .

## 

¡Saludos!
Gonzalo

**Comment by DiegoJimenezTamame** [comment]
Gonzalo, I tried to do that before you guys showed me how to put the script in its place, but I didn't manage to make ir work properly. Could you show me how to asign each midi command to each individual gesture? I don't know how to do that.

**Comment by DiegoJimenezTamame** [comment]
Gonzalo, I tried to do that before you guys showed me how to put the script in its place, but I didn't manage to make ir work properly. Could you show me how to asign each midi command to each individual gesture? I don't know how to do that.

**Comment by DiegoJimenezTamame** [comment]
Sorry, I commented twice

**Comment by tolgraven** [comment]
yeah but as I said main reason would be to not have to choose one or the other. Also thinking there's gotta be some crazy possibilities with the new 9.2 scrub API calls...

**Comment by DiegoJimenezTamame** [comment]
Hi guys! Could you gimme some help here? Do you have any clue on how could I manage to control FX in Ableton with the Pan mode of MYO without having to turn it on/off with the fist gesture? It is extremely difficult to make it remain stable and only affect to the knobs and controls that you need in each precise moment. Any ideas? Thanks so much in advance!

**Comment by GonzaloNV** [comment]
Diego,
That would imply modifying the myo script,since it is programmed to work
like that, otherwise you wouldn't be able to move without affecting the
controls.
You should take a look at the script. It's very simple and it should be
fairly easy to modify to get what you want.
Take a look at the myocraft tutorials. They are a great starting point
